### ISSUE TITLE
Won't run in Gitlab CI

### ISSUE THREAD

**Issue by Xananax** [hayd/deno-docker#49]
I am not sure if this is a bug in this docker, in Gitlab, or me misunderstanding something. Please feel free to close if one of the two latter options.

I'm trying to use the Gitlab CI to build my project using Deno.

Running the CI gives me the following error:

`error: Found argument 'sh' which wasn't expected, or isn't valid in this context`

I get this for any `deno` command that I run, including `deno --version`.

This is my entire CI file:

```yaml
image: hayd/deno

pages:
  stage: deploy
  script:
    - deno --version
    - deno run --unstable --allow-write --allow-read ./scripts/build.ts
  artifacts:
    paths:
      - public
  only:
    - master
```

I get the error twice, once for `deno --version` and once for `deno run`.

I've tried different tags, but they all behave the same.

Note that using [`maxmcd/deno`](https://github.com/maxmcd/deno-docker), my pipeline works, but `maxmcd` is stuck on `0.38`, so `--unstable` doesn't work there (if I remove the need for `--unstable`, the pipeline runs without problems).

Any idea what is going on?

**Comment by hork71** [comment]
perhaps it has something to do with the entrypoint of the image

https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#overriding-the-entrypoint-of-an-image

image: hayd/deno
entrypoint: [""]

**Comment by Xananax** [comment]
That is completely correct, thanks!

For anyone needing this later, here's my modified gitlab-ci (relevant parts):

```yaml
image: 
  name: hayd/deno
  entrypoint: [ "" ]

pages:
  stage: deploy
  script:
    - deno run --unstable --allow-write --allow-read ./scripts/build.ts
  artifacts:
    paths:
      - public
  only:
    - master
```
