### ISSUE TITLE
[Question] Simplify?

### ISSUE THREAD

**Issue by ebebbington** [hayd/deno-docker#79]
Of course this isn't gospel, but i feel thee docker image could be simplified a lot. For example, what i use for my docker environments is:
```
// docker-compose.yml
socket:
    ...
    build:
      context: .
      dockerfile: .docker/deno.dockerfile
      args:
        DENO_VERSION: 1.2.3
    environment:
      USE_DENON: "true"
    ports:
      - "1668:1668"
    volumes:
    - "./src/socket:/var/www/socket"
    working_dir: /var/www/socket
    networks:
      - chatsterisk-app-network
```
```
// .docker/deno.dockerfile
FROM debian:stable-slim

ARG DENO_VERSION

RUN apt update -y \
  && apt clean \
  && apt install bash curl unzip -y

RUN curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=/usr/local sh -s v${DENO_VERSION}
RUN export DENO_INSTALL="/root/.local"
RUN export PATH="$DENO_INSTALL/bin:$PATH"

COPY ./.docker/deno-entrypoint.sh /deno-entrypoint.sh
RUN chmod +x /deno-entrypoint.sh
ENTRYPOINT ["/deno-entrypoint.sh"]
```
```
// deno-entrypoint.sh
// just uses denon if USE_DENON env var is true
```

I think it'd be nice to see aspects of the above incorporated, for example the `ARGS`, so from an end-user perspective, i'd do:

```
// docker-compose.yml
socket:
    image: hayd/deno-image-name
    environment:
        DENO_VERSION: 1.5.6.7 # installs that specific version of deno
```
Whilst maybe still allow the user to specify an entrypoint, so for example i could still install denon and use denon
