### ISSUE TITLE
Allow Passing an Arg for Deno Version

### ISSUE THREAD

**Issue by ebebbington** [hayd/deno-docker#88]
It'd be great if we can pass an arg for a deno version to install, and your dockr image would default to the latest version if one isn't specified, for example this is how i setup my deno dockerfiles to us an arg for the deno version:

```
// docker-compose.yml
...

  server:
    container_name: ...
    build:
      context: .
      dockerfile: .docker/deno.dockerfile
      args:
        DENO_VERSION: 1.4.6 // <-- here
    ...
```
```
// .docker/deno.dockerfile
FROM debian:stable-slim

ARG DENO_VERSION # <-- here

RUN apt update -y \
  && apt clean \
  && apt install bash curl unzip -y

RUN curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=/usr/local sh -s v${DENO_VERSION} # <-- here
```
